fix: parquet read options config class
ASML-Labs/dagster-delta pull request #8
Opened 2024-08-23 14:14 UTC by sverbruggen

2024-08-23 16:41 UTC, ion-elgreco commented on libraries/dagster-delta-polars/dagster_delta_polars_tests/test_type_handler.py
This test should be actually in dagster-delta

2024-08-26 07:50 UTC, sverbruggen commented on libraries/dagster-delta-polars/dagster_delta_polars_tests/test_type_handler.py
Moved it

2024-08-26 08:16 UTC, gfvioli submitted a review, later dismissed
LGTM

2024-08-26 18:07 UTC, ion-elgreco commented on libraries/dagster-delta-polars/dagster_delta_polars_tests/test_type_handler.py
The test should test the DeltaPyarrowIOManager not the Polars one

2024-08-26 18:07 UTC, ion-elgreco requested changes
Test needs to be changed before we can merge

2024-08-26 18:51 UTC, sverbruggen commented on libraries/dagster-delta-polars/dagster_delta_polars_tests/test_type_handler.py
And it's changed to test the right one

2024-08-26 18:52 UTC, ion-elgreco submitted a review, later dismissed

2024-08-26 19:03 UTC, ion-elgreco approved these changes

2024-08-26 19:04 UTC, merged